global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel-zabudskyi'
