version: '3.3'
services:
  mongo_db:
    image: mongo:3.4.10
    volumes:
      - post_db:${DB_FOLDER}
    networks:
      back_net:
        aliases:
          - post_db_container
          - comment_db_container
  ui:
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${HOST_PUMA_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      back_net:
        aliases:
          - post_container
      front_net:
        aliases:
          - post_container
  comment:
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      back_net:
        aliases:
          - comment_container
      front_net:
        aliases:
          - comment_container
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      back_net:
      front_net:

volumes:
  post_db:

networks:
  back_net:
  front_net:
