version: '3.3'
services:
  mongo_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db_container
          - comment_db_container
  ui:
    build: ./ui
    image: ${USERNAME}/ui:2.2
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      reddit:
        aliases:
          - post_container
  comment:
    build: ./ui
    image: ${USERNAME}/comment:1.0
    networks:
      reddit:
        aliases:
          - comment_container
volumes:
  post_db:

networks:
  reddit:
