version: '3.3'
services:
  mongo_db:
    image: mongo:latest
    volumes:
      - post_db:${DB_FOLDER}
    networks:
      back_net:
        aliases:
          - post_db_container
          - comment_db_container
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      back_net:
        aliases:
          - post_container
      front_net:
        aliases:
          - post_container
  comment:
    build: ./ui
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      back_net:
        aliases:
          - comment_container
      front_net:
        aliases:
          - comment_container
volumes:
  post_db:

networks:
  back_net:
  front_net:
